In [98]:
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os

In [99]:
os.chdir('/Users/cherylxiang/Documents/GitHub/demultiplexing-methods/')
print(os.getcwd())

/Users/cherylxiang/Documents/GitHub/demultiplexing-methods

In [100]:
summary_files = glob.glob('results/**/**/summary.csv', recursive=True)
summary_files = list(set(summary_files))

In [101]:
cher_results = {}
for f in summary_files:
    parts = f.split('/')
    method = parts[1]
    dataset = parts[2]
    df = pd.read_csv(f)
    df = df[df['classification'] != 'total']
    cher_results[f"cher_{method}_{dataset}"] = df

In [102]:
#to list all datasets and methods
"""for key, df in cher_results.items():
    print(key)"""

'for key, df in cher_results.items():\n    print(key)'

In [103]:
#to display dfs
"""for key, df in cher_results.items():
    print(key)
    display(df)"""

'for key, df in cher_results.items():\n    print(key)\n    display(df)'

In [104]:
cher_results['cher_demultiplex_mcginnis_ms']

  classification     n      dataset       method
0        doublet   280  mcginnis_ms  demultiplex
1       negative   323  mcginnis_ms  demultiplex
2        singlet  4556  mcginnis_ms  demultiplex

#### Helper Functions

In [105]:
def create_summary_xcol(calls, method, dataset):
    df = pd.read_csv(calls) 
    df = df.rename(columns={'x': 'classification'})
    df = df.drop(columns=('Unnamed: 0'))

    df['classification'] = df['classification'].replace({
        0: 'negative',
        1000: 'doublet'
    })

    df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

    summary = df['classification'].value_counts().reset_index()
    summary.columns = ['classification', 'n']
    summary = summary.sort_values(by='n', ascending=True)
    summary['dataset'] = dataset
    summary['method'] = method
    
    return summary

In [106]:
def create_summary(calls, method, dataset):
    df = pd.read_csv(calls) 
    df = df.rename(columns={'Classification': 'classification'})
    df = df.drop(columns=('Unnamed: 0'))

    df['classification'] = df['classification'].replace({
        0: 'negative',
        1000: 'doublet'
    })

    df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

    summary = df['classification'].value_counts().reset_index()
    summary.columns = ['classification', 'n']
    summary = summary.sort_values(by='n', ascending=True)
    summary['dataset'] = dataset
    summary['method'] = method
    
    return summary

### Dataset 1 Calls Comparison: McGinnis MS

In [107]:
brian_demultiplex_mcginnis_ms = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_demultiplex.csv', 'demultiplex', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_demultiplex_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_demultiplex_mcginnis_ms'])

Brian's Results:

  classification     n      dataset       method
2        doublet   280  mcginnis_ms  demultiplex
1       negative   323  mcginnis_ms  demultiplex
0        singlet  4556  mcginnis_ms  demultiplex

Cheryl's Results:

  classification     n      dataset       method
0        doublet   280  mcginnis_ms  demultiplex
1       negative   323  mcginnis_ms  demultiplex
2        singlet  4556  mcginnis_ms  demultiplex

In [108]:
brian_demultiplex2_mcginnis_ms = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_demultiplex2.csv', 'demultiplex2', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_demultiplex2_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_demultiplex2_mcginnis_ms'])

Brian's Results:

  classification     n      dataset        method
2       negative    88  mcginnis_ms  demultiplex2
1        doublet   374  mcginnis_ms  demultiplex2
0        singlet  4491  mcginnis_ms  demultiplex2

Cheryl's Results:

  classification     n      dataset        method
0        doublet   374  mcginnis_ms  demultiplex2
1       negative   294  mcginnis_ms  demultiplex2
2        singlet  4491  mcginnis_ms  demultiplex2

In [109]:
brian_htodemux_mcginnis_ms = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_htodemux.csv', 'htodemux', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_htodemux_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_htodemux_mcginnis_ms'])

Brian's Results:

  classification     n      dataset    method
2       negative   317  mcginnis_ms  htodemux
1        doublet   530  mcginnis_ms  htodemux
0        singlet  4312  mcginnis_ms  htodemux

Cheryl's Results:

  classification     n      dataset    method
0        doublet   633  mcginnis_ms  htodemux
1       negative   296  mcginnis_ms  htodemux
2        singlet  4230  mcginnis_ms  htodemux

In [110]:
brian_hashsolo_mcginnis_ms = create_summary('brian-scripts/McGinnis_calls/labels_mcginnis_ms_hsolo.csv', 'hashsolo', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_hashsolo_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_hashsolo_mcginnis_ms'])

Brian's Results:

  classification     n      dataset    method
2       negative    75  mcginnis_ms  hashsolo
1        doublet   431  mcginnis_ms  hashsolo
0        singlet  4653  mcginnis_ms  hashsolo

Cheryl's Results:

  classification     n      dataset    method
0        doublet   431  mcginnis_ms  hashsolo
1       negative    75  mcginnis_ms  hashsolo
2        singlet  4653  mcginnis_ms  hashsolo

In [111]:
brian_bffcluster_mcginnis_ms = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_bff_cluster.csv', 'bff_cluster', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_bffcluster_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_bffcluster_mcginnis_ms'])

Brian's Results:

  classification     n      dataset       method
1        doublet   651  mcginnis_ms  bff_cluster
0        singlet  4508  mcginnis_ms  bff_cluster

Cheryl's Results:

  classification     n      dataset       method
0        doublet   651  mcginnis_ms  bff_cluster
1        singlet  4508  mcginnis_ms  bff_cluster

In [112]:
brian_bffraw_mcginnis_ms = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_bff_raw.csv', 'bff_raw', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_bffraw_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_bffraw_mcginnis_ms'])

Brian's Results:

  classification     n      dataset   method
2        doublet   253  mcginnis_ms  bff_raw
1       negative   369  mcginnis_ms  bff_raw
0        singlet  4537  mcginnis_ms  bff_raw

Cheryl's Results:

  classification     n      dataset   method
0        doublet   253  mcginnis_ms  bff_raw
1       negative   369  mcginnis_ms  bff_raw
2        singlet  4537  mcginnis_ms  bff_raw

In [113]:
df = pd.read_csv('brian-scripts/McGinnis_calls/labels_mcginnis_ms_gmmdemux.csv', header=None) 
df = df.rename(columns={0: 'classification'}) 

df['classification'] = df['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary = df['classification'].value_counts().reset_index()
summary.columns = ['classification', 'n']
summary = summary.sort_values(by='n', ascending=True)
summary['dataset'] = 'mcginnis_ms'
summary['method'] = 'gmmdemux'

In [114]:
brian_gmmdemux_mcginnis_ms = summary

print('Brian\'s Results:')
display(brian_gmmdemux_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_gmmdemux_mcginnis_ms'])

Brian's Results:

  classification     n      dataset    method
2        doublet   264  mcginnis_ms  gmmdemux
1       negative   387  mcginnis_ms  gmmdemux
0        singlet  4508  mcginnis_ms  gmmdemux

Cheryl's Results:

  classification     n      dataset    method
0        doublet   283  mcginnis_ms  gmmdemux
1       negative   329  mcginnis_ms  gmmdemux
2        singlet  4547  mcginnis_ms  gmmdemux

In [115]:
brian_hasheddrops_mcginnis_ms = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_hashed.csv', 'hasheddrops', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_hasheddrops_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_hasheddrops_mcginnis_ms'])

Brian's Results:

  classification     n      dataset       method
2       negative   365  mcginnis_ms  hasheddrops
1        doublet   456  mcginnis_ms  hasheddrops
0        singlet  4338  mcginnis_ms  hasheddrops

Cheryl's Results:

  classification     n      dataset       method
0        doublet   456  mcginnis_ms  hasheddrops
1       negative   365  mcginnis_ms  hasheddrops
2        singlet  4338  mcginnis_ms  hasheddrops

In [116]:
brian_demuxmix_mcginnis_ms = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_demuxmix.csv', 'demuxmix', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_demuxmix_mcginnis_ms)
print('Cheryl\'s Results:')
display(cher_results['cher_demuxmix_mcginnis_ms'])

Brian's Results:

  classification     n      dataset    method
2       negative    37  mcginnis_ms  demuxmix
1        doublet   351  mcginnis_ms  demuxmix
0        singlet  4262  mcginnis_ms  demuxmix

Cheryl's Results:

  classification     n      dataset    method
0        doublet   351  mcginnis_ms  demuxmix
1       negative    37  mcginnis_ms  demuxmix
2        singlet  4262  mcginnis_ms  demuxmix

In [117]:
brian_demuxmixnaive_mcginnis_ms	 = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_ms_demuxmix_naive.csv', 'demuxmix naive', 'mcginnis_ms')

print('Brian\'s Results:')
display(brian_demuxmixnaive_mcginnis_ms	)
print('Cheryl\'s Results:')
display(cher_results['cher_demuxmixnaive_mcginnis_ms'])

Brian's Results:

  classification     n      dataset          method
2       negative    37  mcginnis_ms  demuxmix naive
1        doublet   351  mcginnis_ms  demuxmix naive
0        singlet  4262  mcginnis_ms  demuxmix naive

Cheryl's Results:

  classification     n      dataset          method
0        doublet   351  mcginnis_ms  demuxmix naive
1       negative    37  mcginnis_ms  demuxmix naive
2        singlet  4262  mcginnis_ms  demuxmix naive

### Dataset 2 Calls Comparison: McGinnis HTO

In [118]:
brian_demultiplex_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_demultiplex.csv', 'demultiplex', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_demultiplex_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_demultiplex_mcginnis_hto'])

Brian's Results:

  classification     n       dataset       method
2        doublet   760  mcginnis_hto  demultiplex
1       negative  1664  mcginnis_hto  demultiplex
0        singlet  2735  mcginnis_hto  demultiplex

Cheryl's Results:

  classification     n       dataset       method
0        doublet   760  mcginnis_hto  demultiplex
1       negative  1664  mcginnis_hto  demultiplex
2        singlet  2735  mcginnis_hto  demultiplex

In [119]:
brian_demultiplex2_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_demultiplex2.csv', 'demultiplex2', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_demultiplex2_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_demultiplex2_mcginnis_hto'])

Brian's Results:

  classification     n       dataset        method
2        doublet   615  mcginnis_hto  demultiplex2
1       negative   909  mcginnis_hto  demultiplex2
0        singlet  3630  mcginnis_hto  demultiplex2

Cheryl's Results:

  classification     n       dataset        method
0        doublet   615  mcginnis_hto  demultiplex2
1       negative   914  mcginnis_hto  demultiplex2
2        singlet  3630  mcginnis_hto  demultiplex2

In [120]:
brian_htodemux_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_htodemux.csv', 'htodemux', 'mcginnis_hto')

#print('Brian\'s Results:')
display(brian_htodemux_mcginnis_hto)
#print('Cheryl\'s Results:')
display(cher_results['cher_htodemux_mcginnis_hto'])

  classification     n       dataset    method
2        singlet    76  mcginnis_hto  htodemux
1       negative   269  mcginnis_hto  htodemux
0        doublet  4814  mcginnis_hto  htodemux

  classification     n       dataset    method
0        doublet  4867  mcginnis_hto  htodemux
1       negative   260  mcginnis_hto  htodemux
2        singlet    32  mcginnis_hto  htodemux

In [121]:
brian_hashsolo_mcginnis_hto = create_summary('brian-scripts/McGinnis_calls/labels_mcginnis_hto_hsolo.csv', 'hashsolo', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_hashsolo_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_hashsolo_mcginnis_hto'])

Brian's Results:

  classification     n       dataset    method
1        doublet   302  mcginnis_hto  hashsolo
0        singlet  4857  mcginnis_hto  hashsolo

Cheryl's Results:

  classification     n       dataset    method
0        doublet   302  mcginnis_hto  hashsolo
1        singlet  4857  mcginnis_hto  hashsolo

In [122]:
brian_bffcluster_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_bff_cluster.csv', 'bff_cluster', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_bffcluster_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_bffcluster_mcginnis_hto'])

Brian's Results:

  classification     n       dataset       method
2       negative     5  mcginnis_hto  bff_cluster
1        doublet   983  mcginnis_hto  bff_cluster
0        singlet  4171  mcginnis_hto  bff_cluster

Cheryl's Results:

  classification     n       dataset       method
0        doublet   983  mcginnis_hto  bff_cluster
1       negative     5  mcginnis_hto  bff_cluster
2        singlet  4171  mcginnis_hto  bff_cluster

In [123]:
brian_bffraw_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_bff_raw.csv', 'bff_raw', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_bffraw_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_bffraw_mcginnis_hto'])

Brian's Results:

  classification     n       dataset   method
2        singlet    14  mcginnis_hto  bff_raw
1       negative   229  mcginnis_hto  bff_raw
0        doublet  4916  mcginnis_hto  bff_raw

Cheryl's Results:

  classification     n       dataset   method
0        doublet  4916  mcginnis_hto  bff_raw
1       negative   229  mcginnis_hto  bff_raw
2        singlet    14  mcginnis_hto  bff_raw

In [124]:
df2 = pd.read_csv('brian-scripts/McGinnis_calls/labels_mcginnis_hto_gmmdemux.csv', header=None) 
df2 = df2.rename(columns={0: 'classification'}) 

df2['classification'] = df2['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df2.loc[~df2['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary2 = df2['classification'].value_counts().reset_index()
summary2.columns = ['classification', 'n']
summary2 = summary2.sort_values(by='n', ascending=True)
summary2['dataset'] = 'mcginnis_hto'
summary2['method'] = 'gmmdemux'

In [125]:
brian_gmmdemux_mcginnis_hto = summary2

print('Brian\'s Results:')
display(brian_gmmdemux_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_gmmdemux_mcginnis_hto'])

Brian's Results:

  classification     n       dataset    method
1       negative  1787  mcginnis_hto  gmmdemux
0        doublet  3372  mcginnis_hto  gmmdemux

Cheryl's Results:

  classification     n       dataset    method
0        doublet  4923  mcginnis_hto  gmmdemux
1       negative   207  mcginnis_hto  gmmdemux
2        singlet    29  mcginnis_hto  gmmdemux

In [126]:
brian_hasheddrops_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_hashed.csv', 'hasheddrops', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_hasheddrops_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_hasheddrops_mcginnis_hto'])

Brian's Results:

  classification     n       dataset       method
2        doublet   454  mcginnis_hto  hasheddrops
1        singlet  1147  mcginnis_hto  hasheddrops
0       negative  3558  mcginnis_hto  hasheddrops

Cheryl's Results:

  classification     n       dataset       method
0        doublet   454  mcginnis_hto  hasheddrops
1       negative  3558  mcginnis_hto  hasheddrops
2        singlet  1147  mcginnis_hto  hasheddrops

In [127]:
brian_demuxmix_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_demuxmix.csv', 'demuxmix', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_demuxmix_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_demuxmix_mcginnis_hto'])

Brian's Results:

  classification     n       dataset    method
2        doublet   664  mcginnis_hto  demuxmix
1       negative  1421  mcginnis_hto  demuxmix
0        singlet  2565  mcginnis_hto  demuxmix

Cheryl's Results:

  classification     n       dataset    method
0        doublet   664  mcginnis_hto  demuxmix
1       negative  1421  mcginnis_hto  demuxmix
2        singlet  2565  mcginnis_hto  demuxmix

In [128]:
brian_demuxmixnaive_mcginnis_hto = create_summary_xcol('brian-scripts/McGinnis_calls/labels_mcginnis_hto_demuxmix_naive.csv', 'demuxmix naive', 'mcginnis_hto')

print('Brian\'s Results:')
display(brian_demuxmixnaive_mcginnis_hto)
print('Cheryl\'s Results:')
display(cher_results['cher_demuxmixnaive_mcginnis_hto'])

Brian's Results:

  classification     n       dataset          method
2        doublet   664  mcginnis_hto  demuxmix naive
1       negative  1421  mcginnis_hto  demuxmix naive
0        singlet  2565  mcginnis_hto  demuxmix naive

Cheryl's Results:

  classification     n       dataset          method
0        doublet   664  mcginnis_hto  demuxmix naive
1       negative  1421  mcginnis_hto  demuxmix naive
2        singlet  2565  mcginnis_hto  demuxmix naive

### Winkler Datasets

In [129]:
#winkler_pdx1a
brian_bffcluster_winkler_pdx1a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1a_bff_cluster.csv', 'bff_cluster', 'winkler_pdx1a')
brian_bffraw_winkler_pdx1a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1a_bff_raw.csv', 'bff_raw', 'winkler_pdx1a')
brian_demultiplex_winkler_pdx1a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1a_demultiplex.csv', 'demultiplex', 'winkler_pdx1a')
brian_demultiplex2_winkler_pdx1a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1a_demultiplex2.csv', 'demultiplex2', 'winkler_pdx1a')
brian_hasheddrops_winkler_pdx1a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1a_hasheddrops.csv', 'hasheddrops', 'winkler_pdx1a')
brian_hashsolo_winkler_pdx1a = create_summary('brian-scripts/Winkler_calls/labels_winkler_pdx1a_hashsolo.csv', 'hashsolo', 'winkler_pdx1a')
brian_htodemux_winkler_pdx1a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1a_htodemux.csv', 'htodemux', 'winkler_pdx1a')

In [130]:
df = pd.read_csv('brian-scripts/Winkler_calls/labels_winkler_pdx1a_gmmdemux.csv', header=None) 
df = df.rename(columns={0: 'classification'}) 

df['classification'] = df['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary = df['classification'].value_counts().reset_index()
summary.columns = ['classification', 'n']
summary = summary.sort_values(by='n', ascending=True)
summary['dataset'] = 'winkler_pdx1a'
summary['method'] = 'gmmdemux'

brian_gmmdemux_winkler_pdx1a = summary
brian_gmmdemux_winkler_pdx1a

  classification     n        dataset    method
2        singlet    10  winkler_pdx1a  gmmdemux
1       negative   333  winkler_pdx1a  gmmdemux
0        doublet  1441  winkler_pdx1a  gmmdemux

In [131]:
#winkler_pdx1b
brian_bffcluster_winkler_pdx1b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1b_bff_cluster.csv', 'bff_cluster', 'winkler_pdx1b')
brian_bffraw_winkler_pdx1b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1b_bff_raw.csv', 'bff_raw', 'winkler_pdx1b')
brian_demultiplex_winkler_pdx1b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1b_demultiplex.csv', 'demultiplex', 'winkler_pdx1b')
brian_demultiplex2_winkler_pdx1b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1b_demultiplex2.csv', 'demultiplex2', 'winkler_pdx1b')
brian_hasheddrops_winkler_pdx1b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1b_hasheddrops.csv', 'hasheddrops', 'winkler_pdx1b')
brian_hashsolo_winkler_pdx1b = create_summary('brian-scripts/Winkler_calls/labels_winkler_pdx1b_hashsolo.csv', 'hashsolo', 'winkler_pdx1b')
brian_htodemux_winkler_pdx1b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1b_htodemux.csv', 'htodemux', 'winkler_pdx1b')

In [132]:
df = pd.read_csv('brian-scripts/Winkler_calls/labels_winkler_pdx1b_gmmdemux.csv', header=None) 
df = df.rename(columns={0: 'classification'}) 

df['classification'] = df['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary = df['classification'].value_counts().reset_index()
summary.columns = ['classification', 'n']
summary = summary.sort_values(by='n', ascending=True)
summary['dataset'] = 'winkler_pdx1b'
summary['method'] = 'gmmdemux'

brian_gmmdemux_winkler_pdx1b = summary
brian_gmmdemux_winkler_pdx1b

  classification     n        dataset    method
2        singlet    23  winkler_pdx1b  gmmdemux
1       negative   332  winkler_pdx1b  gmmdemux
0        doublet  1581  winkler_pdx1b  gmmdemux

In [133]:
#winkler_pdx1c
brian_bffcluster_winkler_pdx1c = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1c_bff_cluster.csv', 'bff_cluster', 'winkler_pdx1c')
brian_bffraw_winkler_pdx1c = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1c_bff_raw.csv', 'bff_raw', 'winkler_pdx1c')
brian_demultiplex_winkler_pdx1c = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1c_demultiplex.csv', 'demultiplex', 'winkler_pdx1c')
brian_demultiplex2_winkler_pdx1c = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1c_demultiplex2.csv', 'demultiplex2', 'winkler_pdx1c')
brian_hasheddrops_winkler_pdx1c = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1c_hasheddrops.csv', 'hasheddrops', 'winkler_pdx1c')
brian_hashsolo_winkler_pdx1c = create_summary('brian-scripts/Winkler_calls/labels_winkler_pdx1c_hashsolo.csv', 'hashsolo', 'winkler_pdx1c')

In [134]:
df = pd.read_csv('brian-scripts/Winkler_calls/labels_winkler_pdx1c_gmmdemux.csv', header=None) 
df = df.rename(columns={0: 'classification'}) 

df['classification'] = df['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary = df['classification'].value_counts().reset_index()
summary.columns = ['classification', 'n']
summary = summary.sort_values(by='n', ascending=True)
summary['dataset'] = 'winkler_pdx1c'
summary['method'] = 'gmmdemux'

brian_gmmdemux_winkler_pdx1c = summary
brian_gmmdemux_winkler_pdx1c

  classification     n        dataset    method
2        singlet    90  winkler_pdx1c  gmmdemux
1       negative   534  winkler_pdx1c  gmmdemux
0        doublet  1388  winkler_pdx1c  gmmdemux

In [135]:
#winkler_pdx1d
brian_bffcluster_winkler_pdx1d = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1d_bff_cluster.csv', 'bff_cluster', 'winkler_pdx1d')
brian_bffraw_winkler_pdx1d = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1d_bff_raw.csv', 'bff_raw', 'winkler_pdx1d')
brian_demultiplex_winkler_pdx1d = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1d_demultiplex.csv', 'demultiplex', 'winkler_pdx1d')
brian_demultiplex2_winkler_pdx1d = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1d_demultiplex2.csv', 'demultiplex2', 'winkler_pdx1d')
brian_hasheddrops_winkler_pdx1d = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx1d_hasheddrops.csv', 'hasheddrops', 'winkler_pdx1d')
brian_hashsolo_winkler_pdx1d = create_summary('brian-scripts/Winkler_calls/labels_winkler_pdx1d_hashsolo.csv', 'hashsolo', 'winkler_pdx1d')

In [136]:
df = pd.read_csv('brian-scripts/Winkler_calls/labels_winkler_pdx1d_gmmdemux.csv', header=None) 
df = df.rename(columns={0: 'classification'}) 

df['classification'] = df['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary = df['classification'].value_counts().reset_index()
summary.columns = ['classification', 'n']
summary = summary.sort_values(by='n', ascending=True)
summary['dataset'] = 'winkler_pdx1d'
summary['method'] = 'gmmdemux'

brian_gmmdemux_winkler_pdx1d = summary
brian_gmmdemux_winkler_pdx1d

  classification     n        dataset    method
2        singlet    15  winkler_pdx1d  gmmdemux
1       negative   794  winkler_pdx1d  gmmdemux
0        doublet  1108  winkler_pdx1d  gmmdemux

In [137]:
#winkler_pdx3a
brian_bffcluster_winkler_pdx3a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3a_bff_cluster.csv', 'bff_cluster', 'winkler_pdx3a')
brian_bffraw_winkler_pdx3a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3a_bff_raw.csv', 'bff_raw', 'winkler_pdx3a')
brian_demultiplex_winkler_pdx3a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3a_demultiplex.csv', 'demultiplex', 'winkler_pdx3a')
brian_demultiplex2_winkler_pdx3a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3a_demultiplex2.csv', 'demultiplex2', 'winkler_pdx3a')
brian_hasheddrops_winkler_pdx3a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3a_hasheddrops.csv', 'hasheddrops', 'winkler_pdx3a')
brian_hashsolo_winkler_pdx3a = create_summary('brian-scripts/Winkler_calls/labels_winkler_pdx3a_hashsolo.csv', 'hashsolo', 'winkler_pdx3a')
brian_htodemux_winkler_pdx3a = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3a_htodemux.csv', 'htodemux', 'winkler_pdx3a')

In [138]:
df = pd.read_csv('brian-scripts/Winkler_calls/labels_winkler_pdx3a_gmmdemux.csv', header=None) 
df = df.rename(columns={0: 'classification'}) 

df['classification'] = df['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary = df['classification'].value_counts().reset_index()
summary.columns = ['classification', 'n']
summary = summary.sort_values(by='n', ascending=True)
summary['dataset'] = 'winkler_pdx3a'
summary['method'] = 'gmmdemux'

brian_gmmdemux_winkler_pdx3a = summary
brian_gmmdemux_winkler_pdx3a

  classification     n        dataset    method
0       negative  3532  winkler_pdx3a  gmmdemux

In [139]:
#winkler_pdx3b
brian_bffcluster_winkler_pdx3b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3b_bff_cluster.csv', 'bff_cluster', 'winkler_pdx3b')
brian_bffraw_winkler_pdx3b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3b_bff_raw.csv', 'bff_raw', 'winkler_pdx3b')
brian_demultiplex_winkler_pdx3b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3b_demultiplex.csv', 'demultiplex', 'winkler_pdx3b')
brian_demultiplex2_winkler_pdx3b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3b_demultiplex2.csv', 'demultiplex2', 'winkler_pdx3b')
brian_hasheddrops_winkler_pdx3b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3b_hasheddrops.csv', 'hasheddrops', 'winkler_pdx3b')
brian_hashsolo_winkler_pdx3b = create_summary('brian-scripts/Winkler_calls/labels_winkler_pdx3b_hashsolo.csv', 'hashsolo', 'winkler_pdx3b')
brian_htodemux_winkler_pdx3b = create_summary_xcol('brian-scripts/Winkler_calls/labels_winkler_pdx3b_htodemux.csv', 'htodemux', 'winkler_pdx3b')

In [140]:
df = pd.read_csv('brian-scripts/Winkler_calls/labels_winkler_pdx3b_gmmdemux.csv', header=None) 
df = df.rename(columns={0: 'classification'}) 

df['classification'] = df['classification'].replace({
    0: 'negative',
    1000: 'doublet'
})

df.loc[~df['classification'].isin(['negative', 'doublet']), 'classification'] = 'singlet'

summary = df['classification'].value_counts().reset_index()
summary.columns = ['classification', 'n']
summary = summary.sort_values(by='n', ascending=True)
summary['dataset'] = 'winkler_pdx3b'
summary['method'] = 'gmmdemux'

brian_gmmdemux_winkler_pdx3b = summary
brian_gmmdemux_winkler_pdx3b

  classification     n        dataset    method
0       negative  3532  winkler_pdx3b  gmmdemux

In [141]:
brian_results = pd.concat([
   brian_demultiplex_mcginnis_ms,
   brian_demultiplex2_mcginnis_ms,
   brian_htodemux_mcginnis_ms,
   brian_hashsolo_mcginnis_ms,
   brian_bffcluster_mcginnis_ms,
   brian_bffraw_mcginnis_ms,
   brian_gmmdemux_mcginnis_ms,
   brian_hasheddrops_mcginnis_ms,
   brian_demuxmix_mcginnis_ms,
   brian_demuxmixnaive_mcginnis_ms,

   brian_demultiplex_mcginnis_hto, 
   brian_demultiplex2_mcginnis_hto,
   brian_htodemux_mcginnis_hto,
   brian_hashsolo_mcginnis_hto,
   brian_bffcluster_mcginnis_hto,
   brian_bffraw_mcginnis_hto,
   brian_gmmdemux_mcginnis_hto,
   brian_hasheddrops_mcginnis_hto,
   brian_demuxmix_mcginnis_hto,
   brian_demuxmixnaive_mcginnis_hto,

   brian_demultiplex_winkler_pdx1a,
   brian_demultiplex2_winkler_pdx1a,
   brian_htodemux_winkler_pdx1a,
   brian_hashsolo_winkler_pdx1a,
   brian_bffcluster_winkler_pdx1a,
   brian_bffraw_winkler_pdx1a,
   brian_gmmdemux_winkler_pdx1a,
   brian_hasheddrops_winkler_pdx1a,
   
   brian_demultiplex_winkler_pdx1b,
   brian_demultiplex2_winkler_pdx1b,
   brian_htodemux_winkler_pdx1b,
   brian_hashsolo_winkler_pdx1b,
   brian_bffcluster_winkler_pdx1b,
   brian_bffraw_winkler_pdx1b,
   brian_gmmdemux_winkler_pdx1b,
   brian_hasheddrops_winkler_pdx1b,

   brian_demultiplex_winkler_pdx1c,
   brian_demultiplex2_winkler_pdx1c,
   brian_hashsolo_winkler_pdx1c,
   brian_bffcluster_winkler_pdx1c,
   brian_bffraw_winkler_pdx1c,
   brian_gmmdemux_winkler_pdx1c,
   brian_hasheddrops_winkler_pdx1c,

   brian_demultiplex_winkler_pdx1d,
   brian_demultiplex2_winkler_pdx1d,
   brian_hashsolo_winkler_pdx1d,
   brian_bffcluster_winkler_pdx1d,
   brian_bffraw_winkler_pdx1d,
   brian_gmmdemux_winkler_pdx1d,
   brian_hasheddrops_winkler_pdx1d,

   brian_demultiplex_winkler_pdx3a,
   brian_demultiplex2_winkler_pdx3a,
   brian_htodemux_winkler_pdx3a,
   brian_hashsolo_winkler_pdx3a,
   brian_bffcluster_winkler_pdx3a,
   brian_bffraw_winkler_pdx3a,
   brian_gmmdemux_winkler_pdx3a,
   brian_hasheddrops_winkler_pdx3a,

   brian_demultiplex_winkler_pdx3b,
   brian_demultiplex2_winkler_pdx3b,
   brian_htodemux_winkler_pdx3b,
   brian_hashsolo_winkler_pdx3b,
   brian_bffcluster_winkler_pdx3b,
   brian_bffraw_winkler_pdx3b,
   brian_gmmdemux_winkler_pdx3b,
   brian_hasheddrops_winkler_pdx3b,
   ], ignore_index=True)

In [142]:
cher_results = pd.concat(cher_results.values(), ignore_index=True)
cher_df = cher_results[cher_results['classification'] != 'total']

In [146]:
merged_summary = cher_df.merge(
    brian_results,
    on=['dataset', 'method', 'classification'],
    suffixes=('_cher', '_brian'),
    how='outer'
).fillna(0)

# keep only rows where counts differ
discrepancies = merged_summary[merged_summary['n_cher'] != merged_summary['n_brian']].copy()
discrepancies['difference'] = discrepancies['n_cher'] - discrepancies['n_brian']

print(f"Total discrepancies: {len(discrepancies)}")
discrepancies.sort_values(['dataset', 'method', 'classification'])
discrepancies.head()

Total discrepancies: 59

   classification  n_cher       dataset        method  n_brian  difference
10       negative   914.0  mcginnis_hto  demultiplex2    909.0         5.0
18        doublet  4923.0  mcginnis_hto      gmmdemux   3372.0      1551.0
19       negative   207.0  mcginnis_hto      gmmdemux   1787.0     -1580.0
20        singlet    29.0  mcginnis_hto      gmmdemux      0.0        29.0
26        doublet  4867.0  mcginnis_hto      htodemux   4814.0        53.0

In [147]:
# pivot to wide format
discrepancies_wide = discrepancies.pivot_table(
    index=['dataset', 'method'],
    columns='classification',
    values='difference',
    fill_value=0
).reset_index()

# flatten column names
#differences measured in cher - brian
discrepancies_wide.columns.name = None
discrepancies_wide = discrepancies_wide.rename(columns={
    'singlet': 'singlet_diff',
    'multiplet': 'multiplet_diff',
    'negative': 'negative_diff'
})

discrepancies_wide = discrepancies_wide.sort_values(['dataset'], ascending=[True])
discrepancies_wide

          dataset        method  doublet  negative_diff  singlet_diff
0    mcginnis_hto  demultiplex2      0.0            5.0           0.0
1    mcginnis_hto      gmmdemux   1551.0        -1580.0          29.0
2    mcginnis_hto      htodemux     53.0           -9.0         -44.0
3     mcginnis_ms  demultiplex2      0.0          206.0           0.0
4     mcginnis_ms      gmmdemux     19.0          -58.0          39.0
5     mcginnis_ms      htodemux    103.0          -21.0         -82.0
6   winkler_pdx1a      gmmdemux    309.0         -331.0          22.0
7   winkler_pdx1a      htodemux   -422.0          -86.0       -1276.0
8   winkler_pdx1b      gmmdemux     93.0         -318.0         225.0
9   winkler_pdx1b      htodemux   -571.0          -51.0       -1314.0
10  winkler_pdx1c      gmmdemux    544.0         -524.0         -20.0
12  winkler_pdx1d      htodemux    457.0           84.0        1376.0
11  winkler_pdx1d      gmmdemux    736.0         -787.0          51.0
13  winkler_pdx3a   demultiplex      9.0           17.0         -26.0
14  winkler_pdx3a  demultiplex2     -3.0            2.0           1.0
15  winkler_pdx3a      gmmdemux      0.0        -3532.0           0.0
16  winkler_pdx3a   hasheddrops    -20.0          -22.0          42.0
17  winkler_pdx3a      hashsolo      1.0            0.0          -1.0
18  winkler_pdx3a      htodemux  -1667.0         -770.0       -1095.0
19  winkler_pdx3b      gmmdemux      0.0        -3532.0           0.0
20  winkler_pdx3b   hasheddrops    -15.0          -23.0          38.0
21  winkler_pdx3b      hashsolo      3.0            0.0          -3.0
22  winkler_pdx3b      htodemux  -1425.0         -799.0       -1320.0

In [148]:
for _, row in discrepancies_wide.iterrows():
    dataset = row['dataset']
    method = row['method']
    
    print(f"\n{'='*50}")
    print(f"Dataset: {dataset} | Method: {method}")
    print(f"{'='*50}")
    
    # filter from concatenated dataframes
    brian_subset = brian_results[
        (brian_results['dataset'] == dataset) & 
        (brian_results['method'] == method)
    ]
    cher_subset = cher_results[
        (cher_results['dataset'] == dataset) & 
        (cher_results['method'] == method)
    ]
    
    print("Brian's Results:")
    display(brian_subset)
    print("Cheryl's Results:")
    display(cher_subset)

==================================================
Dataset: mcginnis_hto | Method: demultiplex2
==================================================
Brian's Results:

   classification     n       dataset        method
32        doublet   615  mcginnis_hto  demultiplex2
33       negative   909  mcginnis_hto  demultiplex2
34        singlet  3630  mcginnis_hto  demultiplex2

Cheryl's Results:

   classification     n       dataset        method
80        doublet   615  mcginnis_hto  demultiplex2
81       negative   914  mcginnis_hto  demultiplex2
82        singlet  3630  mcginnis_hto  demultiplex2

==================================================
Dataset: mcginnis_hto | Method: gmmdemux
==================================================
Brian's Results:

   classification     n       dataset    method
46       negative  1787  mcginnis_hto  gmmdemux
47        doublet  3372  mcginnis_hto  gmmdemux

Cheryl's Results:

   classification     n       dataset    method
11        doublet  4923  mcginnis_hto  gmmdemux
12       negative   207  mcginnis_hto  gmmdemux
13        singlet    29  mcginnis_hto  gmmdemux

==================================================
Dataset: mcginnis_hto | Method: htodemux
==================================================
Brian's Results:

   classification     n       dataset    method
35        singlet    76  mcginnis_hto  htodemux
36       negative   269  mcginnis_hto  htodemux
37        doublet  4814  mcginnis_hto  htodemux

Cheryl's Results:

    classification     n       dataset    method
161        doublet  4867  mcginnis_hto  htodemux
162       negative   260  mcginnis_hto  htodemux
163        singlet    32  mcginnis_hto  htodemux

==================================================
Dataset: mcginnis_ms | Method: demultiplex2
==================================================
Brian's Results:

  classification     n      dataset        method
3       negative    88  mcginnis_ms  demultiplex2
4        doublet   374  mcginnis_ms  demultiplex2
5        singlet  4491  mcginnis_ms  demultiplex2

Cheryl's Results:

   classification     n      dataset        method
77        doublet   374  mcginnis_ms  demultiplex2
78       negative   294  mcginnis_ms  demultiplex2
79        singlet  4491  mcginnis_ms  demultiplex2

==================================================
Dataset: mcginnis_ms | Method: gmmdemux
==================================================
Brian's Results:

   classification     n      dataset    method
17        doublet   264  mcginnis_ms  gmmdemux
18       negative   387  mcginnis_ms  gmmdemux
19        singlet  4508  mcginnis_ms  gmmdemux

Cheryl's Results:

    classification     n      dataset    method
101        doublet   283  mcginnis_ms  gmmdemux
102       negative   329  mcginnis_ms  gmmdemux
103        singlet  4547  mcginnis_ms  gmmdemux

==================================================
Dataset: mcginnis_ms | Method: htodemux
==================================================
Brian's Results:

  classification     n      dataset    method
6       negative   317  mcginnis_ms  htodemux
7        doublet   530  mcginnis_ms  htodemux
8        singlet  4312  mcginnis_ms  htodemux

Cheryl's Results:

    classification     n      dataset    method
141        doublet   633  mcginnis_ms  htodemux
142       negative   296  mcginnis_ms  htodemux
143        singlet  4230  mcginnis_ms  htodemux

==================================================
Dataset: winkler_pdx1a | Method: gmmdemux
==================================================
Brian's Results:

   classification     n        dataset    method
75        singlet    10  winkler_pdx1a  gmmdemux
76       negative   333  winkler_pdx1a  gmmdemux
77        doublet  1441  winkler_pdx1a  gmmdemux

Cheryl's Results:

    classification     n        dataset    method
133        doublet  1750  winkler_pdx1a  gmmdemux
134       negative     2  winkler_pdx1a  gmmdemux
135        singlet    32  winkler_pdx1a  gmmdemux

==================================================
Dataset: winkler_pdx1a | Method: htodemux
==================================================
Brian's Results:

   classification     n        dataset    method
63       negative    86  winkler_pdx1a  htodemux
64        doublet   422  winkler_pdx1a  htodemux
65        singlet  1276  winkler_pdx1a  htodemux

Cheryl's Results:

Empty DataFrame
Columns: [classification, n, dataset, method]
Index: []

==================================================
Dataset: winkler_pdx1b | Method: gmmdemux
==================================================
Brian's Results:

    classification     n        dataset    method
99         singlet    23  winkler_pdx1b  gmmdemux
100       negative   332  winkler_pdx1b  gmmdemux
101        doublet  1581  winkler_pdx1b  gmmdemux

Cheryl's Results:

    classification     n        dataset    method
136        doublet  1674  winkler_pdx1b  gmmdemux
137       negative    14  winkler_pdx1b  gmmdemux
138        singlet   248  winkler_pdx1b  gmmdemux

==================================================
Dataset: winkler_pdx1b | Method: htodemux
==================================================
Brian's Results:

   classification     n        dataset    method
87       negative    51  winkler_pdx1b  htodemux
88        doublet   571  winkler_pdx1b  htodemux
89        singlet  1314  winkler_pdx1b  htodemux

Cheryl's Results:

Empty DataFrame
Columns: [classification, n, dataset, method]
Index: []

==================================================
Dataset: winkler_pdx1c | Method: gmmdemux
==================================================
Brian's Results:

    classification     n        dataset    method
120        singlet    90  winkler_pdx1c  gmmdemux
121       negative   534  winkler_pdx1c  gmmdemux
122        doublet  1388  winkler_pdx1c  gmmdemux

Cheryl's Results:

    classification     n        dataset    method
130        doublet  1932  winkler_pdx1c  gmmdemux
131       negative    10  winkler_pdx1c  gmmdemux
132        singlet    70  winkler_pdx1c  gmmdemux

==================================================
Dataset: winkler_pdx1d | Method: htodemux
==================================================
Brian's Results:

Empty DataFrame
Columns: [classification, n, dataset, method]
Index: []

Cheryl's Results:

   classification     n        dataset    method
71        doublet   457  winkler_pdx1d  htodemux
72       negative    84  winkler_pdx1d  htodemux
73        singlet  1376  winkler_pdx1d  htodemux

==================================================
Dataset: winkler_pdx1d | Method: gmmdemux
==================================================
Brian's Results:

    classification     n        dataset    method
141        singlet    15  winkler_pdx1d  gmmdemux
142       negative   794  winkler_pdx1d  gmmdemux
143        doublet  1108  winkler_pdx1d  gmmdemux

Cheryl's Results:

   classification     n        dataset    method
38        doublet  1844  winkler_pdx1d  gmmdemux
39       negative     7  winkler_pdx1d  gmmdemux
40        singlet    66  winkler_pdx1d  gmmdemux

==================================================
Dataset: winkler_pdx3a | Method: demultiplex
==================================================
Brian's Results:

    classification     n        dataset       method
147        doublet   161  winkler_pdx3a  demultiplex
148        singlet   955  winkler_pdx3a  demultiplex
149       negative  2416  winkler_pdx3a  demultiplex

Cheryl's Results:

   classification     n        dataset       method
53        doublet   170  winkler_pdx3a  demultiplex
54       negative  2433  winkler_pdx3a  demultiplex
55        singlet   929  winkler_pdx3a  demultiplex

==================================================
Dataset: winkler_pdx3a | Method: demultiplex2
==================================================
Brian's Results:

    classification     n        dataset        method
150        doublet   439  winkler_pdx3a  demultiplex2
151       negative  1350  winkler_pdx3a  demultiplex2
152        singlet  1743  winkler_pdx3a  demultiplex2

Cheryl's Results:

   classification     n        dataset        method
20        doublet   436  winkler_pdx3a  demultiplex2
21       negative  1352  winkler_pdx3a  demultiplex2
22        singlet  1744  winkler_pdx3a  demultiplex2

==================================================
Dataset: winkler_pdx3a | Method: gmmdemux
==================================================
Brian's Results:

    classification     n        dataset    method
164       negative  3532  winkler_pdx3a  gmmdemux

Cheryl's Results:

Empty DataFrame
Columns: [classification, n, dataset, method]
Index: []

==================================================
Dataset: winkler_pdx3a | Method: hasheddrops
==================================================
Brian's Results:

    classification     n        dataset       method
165        doublet   320  winkler_pdx3a  hasheddrops
166        singlet  1214  winkler_pdx3a  hasheddrops
167       negative  1998  winkler_pdx3a  hasheddrops

Cheryl's Results:

    classification     n        dataset       method
176        doublet   300  winkler_pdx3a  hasheddrops
177       negative  1976  winkler_pdx3a  hasheddrops
178        singlet  1256  winkler_pdx3a  hasheddrops

==================================================
Dataset: winkler_pdx3a | Method: hashsolo
==================================================
Brian's Results:

    classification     n        dataset    method
156        doublet   813  winkler_pdx3a  hashsolo
157        singlet  2719  winkler_pdx3a  hashsolo

Cheryl's Results:

    classification     n        dataset    method
110        doublet   814  winkler_pdx3a  hashsolo
111        singlet  2718  winkler_pdx3a  hashsolo

==================================================
Dataset: winkler_pdx3a | Method: htodemux
==================================================
Brian's Results:

    classification     n        dataset    method
153       negative   770  winkler_pdx3a  htodemux
154        singlet  1095  winkler_pdx3a  htodemux
155        doublet  1667  winkler_pdx3a  htodemux

Cheryl's Results:

Empty DataFrame
Columns: [classification, n, dataset, method]
Index: []

==================================================
Dataset: winkler_pdx3b | Method: gmmdemux
==================================================
Brian's Results:

    classification     n        dataset    method
185       negative  3532  winkler_pdx3b  gmmdemux

Cheryl's Results:

Empty DataFrame
Columns: [classification, n, dataset, method]
Index: []

==================================================
Dataset: winkler_pdx3b | Method: hasheddrops
==================================================
Brian's Results:

    classification     n        dataset       method
186        doublet   283  winkler_pdx3b  hasheddrops
187        singlet  1327  winkler_pdx3b  hasheddrops
188       negative  1934  winkler_pdx3b  hasheddrops

Cheryl's Results:

   classification     n        dataset       method
95        doublet   268  winkler_pdx3b  hasheddrops
96       negative  1911  winkler_pdx3b  hasheddrops
97        singlet  1365  winkler_pdx3b  hasheddrops

==================================================
Dataset: winkler_pdx3b | Method: hashsolo
==================================================
Brian's Results:

    classification     n        dataset    method
177        doublet   773  winkler_pdx3b  hashsolo
178        singlet  2771  winkler_pdx3b  hashsolo

Cheryl's Results:

    classification     n        dataset    method
139        doublet   776  winkler_pdx3b  hashsolo
140        singlet  2768  winkler_pdx3b  hashsolo

==================================================
Dataset: winkler_pdx3b | Method: htodemux
==================================================
Brian's Results:

    classification     n        dataset    method
174       negative   799  winkler_pdx3b  htodemux
175        singlet  1320  winkler_pdx3b  htodemux
176        doublet  1425  winkler_pdx3b  htodemux

Cheryl's Results:

Empty DataFrame
Columns: [classification, n, dataset, method]
Index: []